backend:
  name: git-gateway
  repo: joaovsa7/joaovsa.dev
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:

  - name: city_pages
    label: City Pages
    label_singular: City Page
    identifier_field: de.title
    folder: data/city_pages/
    extension: yml
    create: true
    preview_path: "stadt/{{slug}}"
    fields:
      - { label: Title (DE),       name: de.title,       widget: string, required: true }
      - { label: Title (EN),       name: en.title,       widget: string, required: true }
      - { label: Description (DE), name: de.description, widget: text,   required: true }
      - { label: Description (EN), name: en.description, widget: text,   required: true }
      - { label: Tagline (DE),     name: de.tagline,     widget: string, required: true }
      - { label: Tagline (EN),     name: en.tagline,     widget: string, required: true }

  - name: jobs
    label: Jobs
    label_singular: Job
    folder: data/jobs/
    extension: yml
    create: true
    preview_path: "jobs/{{slug}}"
    fields:
      - { label: Title,       name: title,       widget: string, required: true }
      - { label: Date,        name: date,        widget: date,   required: true, format: 'YYYY-MM-DD' }
      - { label: Description, name: description, widget: text,   required: true }